### ISSUE TITLE
icons no show in menu

### ISSUE THREAD

**Issue by MikeSoft** [nathanielw/Android-Lollipop-Pencil-Stencils#13] opened 2016-11-29 19:58 UTC
when i install the package and list the icons it show this. 

![2016-11-29 14_57_44-](https://cloud.githubusercontent.com/assets/1222421/20726580/36620e26-b644-11e6-975e-630706d2d3fa.png)

but when i drag and drop the icons, they appaer o.O

**Comment by shakeeltariq** [comment] 2016-12-04 12:29
I just tried it, it shows like this with broken icons in Pencil 3 but works fine in Pencil 2. Think it needs to be ported to support Pencil 3. 
@nathanielw how can I contribute to help it port to 3 ?

**Comment by nathanielw** [comment] 2016-12-10 02:07
I think this is a duplicate of #10, which (afaik) is a bug in Pencil itself, not the stencil collection. It's been reported in the Pencil repo: https://github.com/evolus/pencil/issues/178

**Closed as completed by nathanielw** 2016-12-10 02:07 UTC
